# 9_3 To `panic!` or not to `panic!`

- 언제 `panic!` 을 쓰고 언제 `Result`를 쓰는지 결정합시다.
  - `panic!`하면 복구 불가능합니다. 어떤 에러 상황에서도 (복구 가능한 방법이
      있건 아니건)  `panic!`을 하도록 결정할 수는 있지만, 그러면 코드가 복구
      불가능하다고 시인하는 것과 다름없습니다.
  - `Result`를 반환하기로 하면, caller에게 옵션을 주는 것이고, caller가 복구할지
      아니면 그 `Err`를 보고 `panic!`할지 결정하게 만들 수 있습니다.
  - 따라서 함수가 실패할 수 있는 환경에서 기본적으로는 `Result`를 쓰는 것이 좋습니다.
    - 그러나 prototype code, 예시 코드, 테스트를 작성할 때는 `panic`을 쓰는 것이
        더 좋습니다. 왜 그런지 살펴보고, 컴파일러는 실패할 수 없다고 확정하지
        못하지만 인간은 실패할 수 없다고 확정할 수 있는 상황들을 살펴봅니다.

## 9_3_1 Examples, Prototype Code, and Tests: okay to panic

- 특정 concept를 설명하는 예시를 작성할 때, 이를 위한 error handling code를
    자세히 작성하면 오히려 코드가 복잡해집니다. Example을 짤 때는, `unwrap` 처럼
    panic 가능한 코드를 호출하는 것이 application이 에러를 처리하려는 방법에
    대한 placeholder로서의 의미를 가지는데, 이는 코드의 나머지 부분이 어떤 것을
    하는지에 따라 달라질 수 있습니다.
- 비슷한 상황에서, `unwrap`, `expect`를 쓰는 것은 프로토타이핑에 유용합니다.
    (에러 핸들링을 어떻게 할지 결정하지 않았을 때) 여러분이 코드를 더 robust하게
    만들 준비가 되었을 때, `unwrap`, `expect` 등은 이를 위한 표식을 남겨둡니다
    (여기부터 처리해라.)
- Test에서 method call이 실패하면, 모든 테스트가 실패하게 만들고 싶을 것입니다.
    심지어 method의 functionality가 test 아래에 있는 것이 아니더라도.
    `panic!`이 테스트를 실패시키는 방법이기 때문에, 여기에서 `unwrap`,
    `expect`를 쓰는 건 정확히 하고자 하는 일과 일치합니다.

## 9_3_2 Cases in Which You Have More Information Than the Compiler

- 또한, `Result`를 썼을 때 반드시 `Ok`가 나오는 로직을 가지고 있을 때,
    컴파일러가 이 로직을 이해하지 못할 때가 있습니다. 이 때는
    `unwrap`/`expect`를 사용합니다.
  - 당신이 부르는 어떤 operation이라도 일반적으로는 실패할 가능성이 있을 때 (당신이 원하는 특정
      상황에서는 논리적으로 일어날 리 없어도), 그 때는 `Result` 값을 가지게
      됩니다.
  - 코드를 직접 뜯어보고 `Err` variant가 생길 수 없는 경우, `unwrap`을 써서
      Result를 바로 벗겨내도 됩니다. 혹은, 에러가 생길 리 없는 이류를 명확하게
      적기 위해 `expect()` 안에 이유를 작성해도 됩니다.
```rust
    use std::net::IpAddr;

    let home: IpAddr = "127.0.0.1"
        .parse()
        .expect("Hardcoded IP address should be valid");
```
- `127.0.0.1`은 하드코딩된 값입니다. `expect`를 써도 전혀 문제가 없는 값이지만,
    하드코딩되어 있다고 해서 이 valid한 문자열이 `parse` method의 return type을
    바꾸지는 않습니다. 여전히 `Result`를 반환하죠. 그리고 컴파일러는 '문자열이
    항상 valid하다'는 것을 모르기 때문에, 우리는 `Err` variant가 가능한 경우와
    마찬가지로 `Result`를 다뤄야 합니다.
  - 이 IP address가 유저로부터 들어와서 실패할 가능성을 가졌다면, Result를 좀 더
      robust하게 다뤘어야 했을 것입니다. IP address가 하드코딩되었다는 가정을
      하는 것은, 반대로 IP address가 하드코딩된 값이 아닐 경우 `expect`를 다른
      에러 핸들링 코드로 바꿔야 한다는 것을 의미합니다.

## 9_3_3 Guidelines for Error Handling

- 코드가 '나쁜 state'에서 끝날 가능성이 있다면, panic하는 것이 좋습니다.
  - _bad state_란, 어떤 가정, 보장된 것, 계약, 혹은 invariant가 때진 상태입니다.
    - 예를 들어 invalid values, contradictory values, missing values가 코드에
      전달되었을 때입니다. 이외에도 다른 케이스가 있는데,
    - _bad state_는 예상하지 못한 상황입니다. 이는 평소 일어나는 상황과
        반대입니다. 예를 들어 유저가 데이터를 잘못된 형태로 입력하는 경우입니다.
    - 당신의 코드가 _bad state_가 발생한 이후에도 _bad state_가 아니라는 믿음을
        가진 상태로 작성되었을 때입니다. (매 step마다 문제를 확인하지 않고)
    - 코드의 현재 상황을 당신이 사용하는 타입으로 적절하게 표현하지 못할
        때입니다. Ch 17에서 더 자세히 다룹니다.

- 누군가 당신의 코드를 호출해서 말이 안 되는 값을 집어넣는다면, 에러를 반환해서
    라이브러리 유저가 하고 싶은 것을 하게 하는 게 가장 좋습니다.
  - 그러나, 이를 반복했을 때 보안이 약해지거나 위해를 끼칠 수 있다면, 바로
      `panic`을 불러서 라이브러리 사용자가 작성한 코드에 버그가 있다고 경고하고
      그들이 개발 중에 고칠 수 있도록 하는 것이 좋습니다.
  - 또한, vice versa 하게, 당신이 제어할 수 없는 외부 코드를 불러서 그 코드가
      invalid state를 반환해서 복구 불가능하게 만드는 경우에도 `panic`하는 것이 좋습니다.

- 반대로, 실패하는 것이 맞다고 예상하는 상황이라면, `Result`를 부르는 것이
    좋습니다.
  - 예를 들어, Parser가 malformed data를 받았다거나, HTTP request가 rate limit에
      도달했다는 status를 반환했다거나 하는 상황들입니다.
  - 이 경우 `Result`를 반환한다는 것은 , 실패는 예상된 상황이며 caller가 어떻게
      대응할지 결정해야만 한다는 것입니다.
- 당신이 작성한 함수가 invalid value를 가지고 불렸을 때 유저를 위험에 빠지게 할
    수 있는 경우, 당신은 value가 valid한지 먼저 검사해야 하고 아닌 경우
    panic해야 합니다.
  - 대부분의 경우 안전을 위해서입니다: 유효하지 않은 데이터를 다룰 경우 코드가
      vulnerability에 노출됩니다.
    - 예를 들어, standard library 사용 시 out of bounds memory access를 일으킬
        경우 반드시 `panic!`을 부르게 됩니다. 현재의 자료구조에 속하지 않는
        메모리에 접근하는 것은 흔한 보안 문제이기 때문입니다.
- 함수들은 종종 _contract_를 가집니다: 함수의 동작은 함수의 input이 특정 조건을
    만족할 경우에만 보장됩니다.
  - _contract_가 위반되었을 경우 panic하는 것은 makes sense합니다: _contract_를
      위반하는 것은 언제나 caller 쪽의 버그임을 나타내며 callee가 명시적으로
      해결하고픈 에러의 종류가 아닙니다. 애초의 callee가 복구할 좋은 방법이
      없습니다. callee를 부르는 프로그래머들이 이 코드를 고쳐야 합니다.
    - _contract_는 반드시 해당 함수의 API 명세서에 설명되어야 합니다. 특히
        contract 위반 시 panic하는 경우.

- 그러나 당신의 모든 함수에 많은 양의 에러 체크를 넣는 것은 너무 자세하고 귀찮은
    일입니다. 다행히도, `type system` (컴파일러의 타입 체커)이 많은 검사를
    해줍니다.
  - 함수가 특정 타입의 parameter를 받는다면, 당신은 컴파일러가 그 타입의 값만
      들어온다는 것을 알고 있다고 확신하고 코드 로직을 작성할 수 있습니다.
  - 예를 들어, `Option` 타입이 아닌 type을 가지고 있다면, 프로그램은 `nothing`이
      아닌 무언가를 가지고 있다고 기대합니다. 따라서 `Some`, `None` 각각에 대한
      handle을 할 필요가 없습니다.
  - 다른 예시로 타입을 `u32`로 표시하는 것이 있습니다. 이 경우 parameter가
      음수일 수 없습니다.

## 9_3_4 Creating Custom Types for Validation

- `type system`을 이용하여 valid value를 가지고 있다는 걸 확신하는 점을 이용해,
    validation을 위한 custom type을 만들 수 있습니다.
  - 예를 들어 `Guessing game`에서 우리는 1 ~ 100 사이의 값을 넣으라고 했습니다.
      그러나 실제 input이 1~100 사이인지를 검증하지 않았으며, positive인지만
      확인했습니다.
    - 1보다 작을 때, 100보다 클 때, 여전히 `too high` / `too low`라도 해도 맞긴
        합니다. 그러나 사용자로 하여금 valid한 input을 넣도록 이끌고, invalid한
        input의 종류에 따라 다른 종류의 output을 하는 것이 사용자를 더 도울 수
        있습니다. 예를 들면, out of range 와, digit이 아닌 값을 넣었을 때 다른
        동작을 하도록 합니다.
```rust
    loop {
        // --snip--

        let guess: i32 = match guess.trim().parse() { // u32를 받는 대신.
            Ok(num) => num,
            Err(_) => continue, // digit이 아닌 값이 들어왔으므로 다시 입력.
        };

        if guess < 1 || guess > 100 {
            println!("The secret number will be between 1 and 100.");
            continue;
        }

        match guess.cmp(&secret_number) {
            // --snip--
    }
```

- 그러나 이 solution이 가장 좋은 solution이지는 않습니다.
  - 예를 들어 프로그램이 1~100 사이에서만 동작하여 이런 requirement를 많은
      함수들이 가지고 있었다면, 이런 check를 모든 함수에 집어넣는 것은 매우
      tedious하고, 프로그램 퍼포먼스에 영향을 줄 수 있습니다.
- 그 대신, 타입을 새로 만들어서, validation을 통과한 값만을 해당 타입에 넣어서
    새로운 instance를 만들게 합니다. 그렇게 하면, 이 타입을 많은 함수들이
    안전하게 사용할 수 있습니다.
  - validation 역시 해당 타입의 함수로 만듭니다.
```rust
pub struct Guess {
    value: i32, // private field이므로 Guess struct를 쓰는 코드는 value를 직접
                // 수정할 수 없습니다. 이는 validation을 통과한 값만을
                // 보장합니다.
}

impl Guess {
    pub fn new(value: i32) -> Guess {
        if value < 1 || value > 100 {
            panic!("Guess value must be between 1 and 100, got {}.", value);
        }

        Guess { value } // Value가 1~100 사이인 것이 보장되었으므로 다른 곳에서
        // 검사할 필요가 없습니다.
    }

    pub fn value(&self) -> i32 { // 별도의 동작 없이 값을 반환. getter라고
                                 // 불리기도 함.
                                 // value가 private field이므로 반드시 필요함.
        self.value
    }
}
```

# 9_4 Summary

- Rust의 error handling feature는 당신이 좀 더 robust한 코드를 작성하도록 돕기
    위해 디자인되었습니다.
- `panic!`은 program이 제어할 수 없는 state에 있으며 당신으로 하여금
    invalid/incorrect value를 가지고 프로그램을 지속시키기보다는 process를 멈출
    수 있게 해줍니다.
- `Result` enum은 Rust의 type system을 통해 당신의 코드가 복구 가능한 형태로
    실패하는 operation을 가지고 있다고 알려줍니다.
  - `Result`를 이용해 당신의 코드가 성공했을 때, 실패했을 때 모두를 관리해야
      한다는 것을 알려줄 수 있습니다.
- `panic!`과 `Result`를 적절한 상황에 사용하여 inevitable problem들을 만났을 때
    당신의 코드가 더 믿음직스럽도록 만들 수 있습니다.

# 9_5 Next chapter
- `Option`, `Result` 등의 standard library에 있는 것들이 generic을 사용한다는
    것을 배웠습니다.
- generic이 어떻게 동작하며 코드에서 어떻게 써야 하는지를 Ch 10에서 배웁니다.
